# Generated by Django 2.1.1 on 2018-09-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField()),
                ('question_type', models.CharField(max_length=4)),
                ('question_text', models.CharField(max_length=500)),
                ('choice_a', models.CharField(max_length=100)),
                ('choice_b', models.CharField(max_length=100)),
                ('choice_c', models.CharField(max_length=100)),
                ('choice_d', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=4)),
                ('difficulty', models.IntegerField()),
            ],
        ),
    ]
