# Generated by Django 2.1.2 on 2018-10-21 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20180917_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
