# Generated by Django 2.1.2 on 2018-10-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_num', models.IntegerField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(max_length=4)),
                ('question_text', models.CharField(max_length=5000)),
                ('choice_a', models.CharField(max_length=600)),
                ('choice_b', models.CharField(max_length=600)),
                ('choice_c', models.CharField(max_length=600)),
                ('choice_d', models.CharField(max_length=600)),
                ('answer', models.CharField(max_length=4)),
                ('difficulty', models.IntegerField()),
            ],
        ),
    ]
