# Generated by Django 2.1.2 on 2018-10-21 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField()),
                ('question_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='count',
            unique_together={('username', 'question_num')},
        ),
    ]
