# Generated by Django 2.1.4 on 2018-12-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20181021_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='right_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
